version: '3.4'
services:
  web:
    image: adrield/mini-market-api:latest
    ports:
      - 3000:3000
    depends_on:
      - db
      # - redis

  # redis:
  #   image: "redis:7-alpine"
  #   ports:
  #     - 6379
  #   volumes:
  #     - ./tmp/redis_data:/var/lib/redis/data

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    volumes:
      - ./tmp/postgres_data:/var/lib/postgresql/data
