default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV.fetch('DATABASE', 'localhost') %>
  username: <%= ENV.fetch('USERNAME', 'mini_market') %> 
  password: <%= ENV.fetch('PASSWORD', 'minimarket123') %> 
  # host: db
  # username: postgres
  # password: postgres

development:
  <<: *default
  database: mini_market_dev

test:
  <<: *default
  database: mini_market_test

production:
  <<: *default
  database: mini_market
